/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.avista.vues;
import com.avista.controleurs.PiniControleur;
import java.awt.Dimension;

/**
 *
 * @author chafy
 */
public class FPostMAJ extends javax.swing.JFrame {
    
    PiniControleur unPinitC = new PiniControleur();

    /**
     * Creates new form FPostMAJ
     */
    public FPostMAJ() {
        initComponents(); //initialisation des composants (labels, textboxs..)
        this.setTitle("Exfiles_MAJ : Mise à jour d'eXfiles");
        this.setLocationRelativeTo(null);
        this.setSize(new Dimension(411, 286));
        lblDerniereVersion.setText(unPinitC.VersionActuelle()); //écriture (à partir du label) de la version
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDerniereVersion = new javax.swing.JLabel();
        lblDerniereVersionCons = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRechercheMAJ = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblDerniereVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 96, 114, 20));

        lblDerniereVersionCons.setText("La version actuelle :");
        getContentPane().add(lblDerniereVersionCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 69, 120, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\chafy\\Desktop\\avist.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, -1, -1));

        btnRechercheMAJ.setText("Mettre à jour");
        btnRechercheMAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheMAJActionPerformed(evt);
            }
        });
        jPanel1.add(btnRechercheMAJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\chafy\\Desktop\\bandebleu.PNG")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 360, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\chafy\\Desktop\\bandebleu.PNG")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRechercheMAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheMAJActionPerformed
        
        
        FSaveMAJ uneFen = new FSaveMAJ(); //création objet
        this.setVisible(false); //fermeture fenêtre
        uneFen.setVisible(true); //ouverture de celle instancier
    }//GEN-LAST:event_btnRechercheMAJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPostMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPostMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPostMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPostMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPostMAJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRechercheMAJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDerniereVersion;
    private javax.swing.JLabel lblDerniereVersionCons;
    // End of variables declaration//GEN-END:variables
}
